excluded:
  - .build

disabled_rules:
  - colon
  - comma
  - opening_brace
  - trailing_comma
  - trailing_whitespace
  - vertical_whitespace

opt_in_rules:
  - empty_count
  - force_unwrapping

line_length:
  warning: 120
  error: 140

identifier_name:
  min_length:
    warning: 2

type_name:
  min_length:
    warning: 2
